version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:2.148-slim'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
    - './jenkins_data:/var'
volumes:
  jenkins_data:
    driver: local
